disabled_rules:
  - todo
  - trailing_comma
  - nesting
  - opening_brace
  - superfluous_disable_command
  - switch_case_alignment
  - cyclomatic_complexity
  - statement_position
  - closure_spacing
  - function_body_length

type_name:
  excluded:
    - ID

identifier_name:
  excluded:
    - id
    - vc

# paths to ignore during linting.
excluded:
  - CosmoModules/.build # Where Swift Package Manager checks out dependency sources
  - DerivedData  
opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil

custom_rules:
  spaces_over_tabs:
    included: ".*\\.swift"
    name: "Spaces over Tabs"
    regex: "\t"
    message: "Prefer spaces for indents over tabs. See Xcode setting: 'Text Editing' -> 'Indentation'"
    severity: warning
