name: CI - Pre Release
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  swiftlint:
    name: SwiftLint
    uses: ./.github/workflows/lint.yml
    secrets: inherit
  test:
    name: Testing Cosmo
    needs: swiftlint
    uses: ./.github/workflows/tests.yml
    secrets: inherit
  deploy:
    if: github.repository_owner == 'Wabi-Studios'
    name: Deploying Cosmo [Prerelease]
    needs: [swiftlint, test]
    uses: ./.github/workflows/pre-release.yml
    secrets: inherit
