name: CI - Pull Request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  swiftlint:
    name: SwiftLint
    uses: ./.github/workflows/lint.yml
    secrets: inherit
  test:
    name: Testing Cosmo
    needs: swiftlint
    uses: ./.github/workflows/tests.yml
    secrets: inherit
