name: SwiftLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:

jobs:
  SwiftLint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for SwiftLint
        run: swiftlint --strict
