name: Release Drafter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allow running it manually in case we forget to label a PR before merging
  workflow_dispatch:
  workflow_call:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
