name: Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:
jobs:
  test:
    name: Testing Cosmo
    runs-on: [self-hosted, macOS]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check Version Number exists
        run: exec ./.github/scripts/test_version_number.sh
      - name: Testing App
        run: exec ./.github/scripts/test_app.sh arm
